services:
  macos:
    container_name: macos
    image: ghcr.io/dockur/macos:latest
    environment:
      VERSION: "15"
      RAM_SIZE: "4G"
      CPU_CORES: "1"
      DISK_SIZE: "40G"
      DISK_FMT: "qcow2"
      DISK_CACHE: "writeback"
      DISK_TYPE: "blk"
      RAM_MINIMUM: "2G"
      DISK_MINIMUM: "12G"
      AUDIO: "N"
      DHCP: "N"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - macos-data:/storage
    restart: "no"
    stop_grace_period: 2m

volumes:
  macos-data:
    name: novaos-macos-data
